//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AncientMysteries.Analyzers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AncientMysteries.Analyzers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just fucking do it..
        /// </summary>
        internal static string Analyzer_MakePartial_Description {
            get {
                return ResourceManager.GetString("Analyzer_MakePartial_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make partial.
        /// </summary>
        internal static string Analyzer_MakePartial_MessageFormat {
            get {
                return ResourceManager.GetString("Analyzer_MakePartial_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing partial keyword.
        /// </summary>
        internal static string Analyzer_MakePartial_Title {
            get {
                return ResourceManager.GetString("Analyzer_MakePartial_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add metadata for DescImgGenerator..
        /// </summary>
        internal static string Analyzer_MissingMetadata_Description {
            get {
                return ResourceManager.GetString("Analyzer_MissingMetadata_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add metadata attributes for Items.
        /// </summary>
        internal static string Analyzer_MissingMetadata_MessageFormat {
            get {
                return ResourceManager.GetString("Analyzer_MissingMetadata_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing metadata attributes.
        /// </summary>
        internal static string Analyzer_MissingMetadata_Title {
            get {
                return ResourceManager.GetString("Analyzer_MissingMetadata_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add prefix to classify this texture..
        /// </summary>
        internal static string Analyzer_UnclassifiedTexture_Description {
            get {
                return ResourceManager.GetString("Analyzer_UnclassifiedTexture_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclassified Texture: {0}.
        /// </summary>
        internal static string Analyzer_UnclassifiedTexture_MessageFormat {
            get {
                return ResourceManager.GetString("Analyzer_UnclassifiedTexture_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add prefix to classify this texture.
        /// </summary>
        internal static string Analyzer_UnclassifiedTexture_Title {
            get {
                return ResourceManager.GetString("Analyzer_UnclassifiedTexture_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do it..
        /// </summary>
        internal static string Analyzer_UnifyItemNamespace_Description {
            get {
                return ResourceManager.GetString("Analyzer_UnifyItemNamespace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unify Item Namespace to &apos;AncientMysteries.Items&apos;.
        /// </summary>
        internal static string Analyzer_UnifyItemNamespace_MessageFormat {
            get {
                return ResourceManager.GetString("Analyzer_UnifyItemNamespace_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unify Item Namespace to &apos;AncientMysteries.Items&apos;.
        /// </summary>
        internal static string Analyzer_UnifyItemNamespace_Title {
            get {
                return ResourceManager.GetString("Analyzer_UnifyItemNamespace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use content reference to avoid bugs caused by rename/delete..
        /// </summary>
        internal static string Analyzer_UseContentRef_Description {
            get {
                return ResourceManager.GetString("Analyzer_UseContentRef_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace to {0}.
        /// </summary>
        internal static string Analyzer_UseContentRef_MessageFormat {
            get {
                return ResourceManager.GetString("Analyzer_UseContentRef_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Content Reference.
        /// </summary>
        internal static string Analyzer_UseContentRef_Title {
            get {
                return ResourceManager.GetString("Analyzer_UseContentRef_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make partial.
        /// </summary>
        internal static string CodeFix_MakePartial_Title {
            get {
                return ResourceManager.GetString("CodeFix_MakePartial_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing Metadata Attributes.
        /// </summary>
        internal static string CodeFix_MissingMetadata_Title {
            get {
                return ResourceManager.GetString("CodeFix_MissingMetadata_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unify Item Namespace.
        /// </summary>
        internal static string CodeFix_UnifyItemNamespace_Title {
            get {
                return ResourceManager.GetString("CodeFix_UnifyItemNamespace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Content Reference.
        /// </summary>
        internal static string CodeFix_UseContentRef_Title {
            get {
                return ResourceManager.GetString("CodeFix_UseContentRef_Title", resourceCulture);
            }
        }
    }
}
