using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using Microsoft.Xna.Framework.Graphics;
using System.Runtime.CompilerServices;
using DuckGame;
using static AncientMysteries.groupNames;
using AncientMysteries.Localization.Enums;
using AncientMysteries.AmmoTypes;
using AncientMysteries.Localization;
using AncientMysteries.Bullets;
using AncientMysteries.Utilities;
using static AncientMysteries.AMFonts;

namespace AncientMysteries
{
    public static partial class Texs
    {
        public const string Skull = "skull.png";
        public const string ElectronicImpacter = "ElectronicImpacter.png";
        public const string ShadowDance = "shadowDance.png";
        public const string AxeOfInferno = "axeOfInferno.png";
        public const string HatHatty = "hatHatty.png";
        public const string ThunderStorm = "ThunderStorm.png";
        public const string ElectronicStar = "ElectronicStar.png";
        public const string CrystalExplosionP = "crystalExplosionP.png";
        public const string DarkLord = "darkLord.png";
        public const string MistyShadow = "mistyShadow.png";
        public const string ForceUpdate = "forceUpdate.png";
        public const string FallGuy = "FallGuy.png";
        public const string ShadowwalkerHelmetPickup = "shadowwalkerHelmetPickup.png";
        public const string ShadowBullet = "shadowBullet.png";
        public const string NovaFrm2 = "novaFrm2.png";
        public const string ShadowwalkerChestplateAnimOver = "shadowwalkerChestplateAnimOver.png";
        public const string CubicBlast = "CubicBlast.png";
        public const string ShadowwalkerHelmet = "shadowwalkerHelmet.png";
        public const string Fireball2 = "fireball2.png";
        public const string IcyFlame = "icyFlame.png";
        public const string Firebally = "firebally.png";
        public const string IcySpirit = "icySpirit.png";
        public const string ShadowwalkerBoots = "shadowwalkerBoots.png";
        public const string Judgement = "judgement.png";
        public const string SmallStick = "smallStick.png";
        public const string SilverSword = "silverSword.png";
        public const string HatHattyPickup = "hatHattyPickup.png";
        public const string SilverFang = "silverFang.png";
        public const string BigStick = "bigStick.png";
        public const string ArcaneNova = "arcaneNova.png";
        public const string EF = "eF.png";
        public const string Cross = "cross.png";
        public const string HolyLight = "holyLight.png";
        public const string TrackingGrenade = "trackingGrenade.png";
        public const string WrathBullet = "wrathBullet.png";
        public const string SpearOfLeonidas = "SpearOfLeonidas.png";
        public const string DeathBringer = "DeathBringer.png";
        public const string Glacier = "glacier.png";
        public const string HatBoring3 = "HatBoring3.png";
        public const string RainbowGun = "rainbowGun.png";
        public const string Firebolt = "firebolt.png";
        public const string NovaFrm = "novaFrm.png";
        public const string Crystal = "crystal.png";
        public const string Icicle = "icicle.png";
        public const string NanoMine = "nanoMine.png";
        public const string FuriousNewYear = "FuriousNewYear.png";
        public const string CrystalFrm = "crystalFrm.png";
        public const string ShadowwalkerChestplatePickup = "shadowwalkerChestplatePickup.png";
        public const string OceansRage = "oceansRage.png";
        public const string SkullR = "skullR.png";
        public const string ShadowwalkerBootsPickup = "shadowwalkerBootsPickup.png";
        public const string HolyStar = "holyStar.png";
        public const string FallGuyMark = "FallGuyMark.png";
        public const string SpyKnife = "spyKnife.png";
        public const string HatBoring3Pickup = "HatBoring3Pickup.png";
        public const string Dice = "dice.png";
        public const string FerociousPredator = "ferociousPredator.png";
        public const string PriLibram = "priLibram.png";
        public const string VoidPiercer = "VoidPiercer.png";
        public const string TheMystery = "theMystery.png";
        public const string ReboundShield = "reboundShield.png";
        public const string ShadowwalkerChestplateAnim = "shadowwalkerChestplateAnim.png";
        public const string CrystalExplosion = "crystalExplosion.png";
        public const string MoltenSpitter = "MoltenSpitter.png";
        public const string HolyLight2 = "holyLight2.png";
        public const string NovaFrm3 = "novaFrm3.png";
        public const string Nova4 = "nova4.png";
        public const string DarkAurora = "darkAurora.png";
        public const string TargetCircle = "targetCircle.png";
    }

}
