global using AncientMysteries.AmmoTypes;
global using AncientMysteries.Bullets;
global using AncientMysteries.Items;
global using AncientMysteries.Localization;
global using AncientMysteries.Localization.Enums;
global using AncientMysteries.Particles;
global using AncientMysteries.Utilities;
global using DuckGame;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using static AncientMysteries.AMFonts;
global using static AncientMysteries.ContentReferences;
global using static AncientMysteries.groupNames;
global using static AncientMysteries.Utilities.InputHelper;
global using static AncientMysteries.Utilities.Math2;
global using SFX = AncientMysteries.Utilities.SFX2;