global using System;
global using DuckGame;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using AncientMysteries.Items;
global using AncientMysteries.Utilities;
global using AncientMysteries.AmmoTypes;
global using AncientMysteries.Bullets;
global using AncientMysteries.Particles;
global using AncientMysteries.Localization;
global using AncientMysteries.Localization.Enums;
global using static AncientMysteries.groupNames;
global using static AncientMysteries.Texs;
