global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using SkiaSharp;
global using Topten.RichTextKit;
global using System.Reflection;
global using Mono.Cecil;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using static DescImgGenerator.ModMetaReader;
global using static DescImgGenerator.Helper;
global using static DescImgGenerator.ImgStyles;